### ISSUE TITLE
Convert setup.py to pyproject.toml

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari-tiff#13]
When this repository was first created, `setup.py` files were the standard way to package your python projects. Now the current best practice is to use `pypoject.toml` setup files instead. So, we want to convert the `setup.py` file here into a `pyproject.toml` file.

Extra resources: the python packaging user guide https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by jni** [comment]
There's a tool to automate the bulk of this, gimme a sec to find it...

**Comment by jni** [comment]
https://github.com/diazona/setuptools-pyproject-migration
