### ISSUE TITLE
Respecting SamplesPerPixels in OME.Tiff

### ISSUE THREAD

**Issue by MosGeo** [napari/napari-tiff#36]
I am coming to the conclusion that napari-tiff is not repecting the SamplesPerPixel flag. The example attached is a simple one that I generated using tiffile. As you can see, the SamplesPerPixels is 3. When the image is loaded with napari-tiff, the RGB channels are loaded seperatly as layers which is not what I expected. Am I doing something wrong in saving the file and the metadata?

[astronaut.ome.zip](https://github.com/user-attachments/files/16977024/astronaut.ome.zip)

This is the OME for it:
![image](https://github.com/user-attachments/assets/088a69a0-b533-45bd-b1d8-0ffceb64a259)

**Comment by MosGeo** [comment]
Ok. I will take a stab at it.

**Comment by MosGeo** [comment]
On further examination, I found that the image that I am saving does not explicitly indicate that the photometric as RGB. Tifffile is not detecting that by default either. This causes napari-tiff to have `is_rgb` as false because of this line
`is_rgb = series.keyframe.photometric == PHOTOMETRIC.RGB and nchannels in (3, 4)`

Once I fixed my export pipeline, the images are displayed as RGB as expected.

You can close this issue for now. I suspect that more complex images will still require SamplesPerPixels variable to subdivide them correctly but not for simple cases.

p.s. thinking about subdividing the channels into groups, the only way I can think of is to have all the C have the same number of SamplesPerPixels in order for it to be reshaped correctly. I don't know how to do it otherwise.

**Comment by jni** [comment]
Thanks for the discussion @MosGeo! I'll close this for now. This plugin is definitely not "finished" and we will keep adding improvements as we encounter the need, so keep the reports coming! 😊
